version: '3.8' 
services:
  app:
    build: .
    container_name: gemini-proxy-panel-node 
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./database.db:/usr/src/app/database.db
